#!/ bin / bash
format_file()
{
    file = "${1}" clang - format - i $ { 1 }
    git add $ { 1 }
}

case "${1}" in
	--about )
		echo "Runs clang-format on source files"
		;;
	* )
		for file in `git diff-index --cached --name-only HEAD` ; do
			format_file "${file}"
		done
		;;
esac
